<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>source.icl</string>
        <key>fileTypes</key>
        <array>
            <string>icl</string>
        </array>
        <key>name</key>
        <string>ICL file</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#import</string>
            </dict>
            <dict>
                <key>comment</key>
                <string>Matches settings blocks references</string>
                <key>include</key>
                <string>#settings-block-identifier</string>
            </dict>
            <!--settings block aliases e.g. HttpPort -->
            <dict>
                <key>comment</key>
                <string>Matches alias declarations</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.js</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>support.type.object.module.js</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.js</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>\b(as) ([a-z|A-Z]+)[\s]+(from)?</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#heredoc</string>
            </dict>
            <!--apply a mixin via identifier -->
            <dict>
                <key>comment</key>
                <string>Matches mixin calls with identifier</string>
                <key>include</key>
                <string>#apply</string>
            </dict>
            <!--apply a mixin via it's alias
            <dict><key>comment</key><string>Matches mixin calls with alias</string><key>captures</key><dict><key>1</key><dict><key>name</key><string>storage.type</string></dict><key>2</key><dict><key>name</key><string>entity.name.function</string></dict></dict><key>match</key><string>\b(apply)\b \b([a-z|A-Z|_]+[a-z|A-Z|0-9|-]*)\b</string></dict> -->
            <!--from/table keywords -->
            <dict>
                <key>comment</key>
                <string>Matches from inheritance declarations</string>
                <key>match</key>
                <string>\b(?i:(from|table))\b</string>
                <key>name</key>
                <string>storage.type</string>
            </dict>
            <!--library settings block -->
            <dict>
                <key>match</key>
                <string>(::[a-z|A-Z|_|-]+[a-z|A-Z|_|-|0-9]+)\b</string>
                <key>name</key>
                <string>support.type.object.module.js</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <!--<string>keyword.control.export.js</string>-->
                        <string>keyword.control</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>variable.language.prototype.js</string>
                    </dict>
                </dict>
                <key>comment</key>
                <string>match a settings block type</string>
                <key>match</key>
                <string>([a-z|A-Z|_]+[a-z|A-Z|0-9])(?:(\s+"[a-z|A-Z|_]+[a-z|A-Z|0-9|-]+"))</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.numeric</string>
                <key>match</key>
                <string>"\b(0x[0-9A-Fa-f]+)([kKmMgG]b?)?\b"|'\b(0x[0-9A-Fa-f]+)([kKmMgG]b?)?\b'</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.numeric</string>
                <key>match</key>
                <string>"\b([0-9]+)([kKmMgG]b?)?\b"|'\b([0-9]+)([kKmMgG]b?)?\b'</string>
            </dict>
            <dict>
                <key>match</key>
                <string>("[a-z|A-Z|_|\-|0-9]+")</string>
                <key>name</key>
                <string>string</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
                <key>name</key>
                <string>constant.numeric</string>
            </dict>
            <dict>
                <key>name</key>
                <string>comment.block</string>
                <key>begin</key>
                <string>\/\*</string>
                <key>end</key>
                <string>\*\/</string>
            </dict>
            <dict>
                <key>name</key>
                <string>comment.line</string>
                <key>match</key>
                <string>(//|#).*$</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.parameter.function.js</string>
                <key>match</key>
                <string>((@@|@)[a-z|A-Z|_]+[a-z|A-Z|_|\.|0-9]*)</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string.quoted.single.js</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(@)(".+")</string>
            </dict>
            <dict>
                <key>name</key>
                <string>string.quoted.single.js</string>
                <key>match</key>
                <string>"[^"]+"</string>
                <!--<array><dict><key>include</key><string>#escapes</string></dict><dict><key>match</key><string>"[^"]+"</string></dict><dict><key>match</key><string>\n</string><key>name</key><string>constant.character.escape.newline.js</string></dict><dict><key>match</key><string>\n</string><key>name</key><string>invalid.illegal.character-not-allowed-here.js</string></dict></array>-->
            </dict>
            <dict>
                <key>name</key>
                <string>constant.language</string>
                <key>match</key>
                <string>\b(true|false|null)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.numeric</string>
                <key>match</key>
                <string>\b([0-9]+)\b</string>
            </dict>
            <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.separator.object.js</string>
            </dict>
            <!--<dict><key>include</key><string>source.js</string></dict>-->
        </array>
        <key>repository</key>
        <dict>
            <key>heredoc</key>
            <!--<dict><key>match</key><string>\s*(<<<\s?(\w+))</string><key>name</key><string>keyword.control.import.js</string></dict>-->
            <dict>
                <key>begin</key>
                <string>\s*(<<<\s?(\w+))</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>string.unquoted.label.js</string>
                    </dict>
                    <!--<key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.import.js</string>
                    </dict>-->
                </dict>
                <key>end</key>
                <string>\2$</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>string.unquoted.label.js</string>
                    </dict>
                </dict>
            </dict>
            <!-- import -->
            <key>import</key>
            <dict>
                <key>begin</key>
                <string>\b(take)(?!\s*:)\b</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.import.js</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>\n|(?=//)</string>
                <key>endCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.terminator.statement.js</string>
                    </dict>
                </dict>
            </dict>
            <!--settings block identifier -->
            <key>settings-block-identifier</key>
            <dict>
                <key>match</key>
                <string>([a-z|A-Z|_]+[a-z|A-Z|0-9|-]*)(\.([a-z|A-Z|_]+[a-z|A-Z|0-9|-]*))</string>
                <key>name</key>
                <string>entity.name.type</string>
            </dict>
            <!-- call a mixin settings block by it's alias -->
            <key>apply</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>storage.type</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>entity.name.type</string>
                            </dict>
                        </dict>
                        <key>match</key>
                        <string>(\b(apply)\b \b(([a-z|A-Z|_]+[a-z|A-Z|0-9|-]*)(\.([a-z|A-Z|_]+[a-z|A-Z|0-9|-]*))+)\b)</string>
                    </dict>
                    <dict>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>storage.type</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>entity.name.type</string>
                            </dict>
                        </dict>
                        <key>match</key>
                        <string>(\b(apply)\b \b([a-z|A-Z|_]+[a-z|A-Z|0-9|-]*)\b)</string>
                    </dict>
                </array>
            </dict>
        </dict>
        <key>uuid</key>
        <string>ba09dd43-8778-4e39-9239-56c560a8c129</string>
    </dict>
</plist>